version: '3.8'  # Use the highest version from the original files

services:
  mysql-master:
    image: mysql:8.0.37-debian
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_REPLICATION_USER: root
      MYSQL_REPLICATION_PASSWORD: 123456
      TZ: Asia/Ho_Chi_Minh
    command:
      - --default-authentication-plugin=mysql_native_password
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
    volumes:
      - mysql-master-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - do_an

networks:
  do_an:
    driver: bridge

volumes:
  mysql-master-data:
